services:
  app:
    container_name: app
    build:
      context: ./docker
    image: devarcade
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
  db:
    container_name: database
    image: mariadb:10.4.28
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
      - ./src/buildDatabase.sql:/docker-entrypoint-initdb.d/buildDatabase.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DevArcade
      MYSQL_USER: devarcade
      MYSQL_PASSWORD: devarcade
      TZ: America/Los_Angeles

volumes:
  mysql-data: